### ISSUE TITLE
Client.Timeout exceeded error when adding a few thousand documents to the index

### ISSUE THREAD

**Issue by deshetti** [meilisearch/meilisearch-go#45]
I am trying to add around 25K documents to the index and getting the following error when doing so. 

```
unable to execute request (path "PUT /indexes/players/documents" with method "Documents.AddOrUpdate"): Put "http://localhost:7700/indexes/players/documents": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

When I use the functions, DefaultWaitForPendingUpdate or , I get the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e23d4]

goroutine 1 [running]:
github.com/meilisearch/meilisearch-go.Client.WaitForPendingUpdate(0x15f2cc8, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3b9aca00, ...)
	/Users/deshetti/go/pkg/mod/github.com/meilisearch/meilisearch-go@v0.9.1/client.go:257 +0x104
github.com/meilisearch/meilisearch-go.Client.DefaultWaitForPendingUpdate(0x15f2cc8, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3b9aca00, ...)
	/Users/deshetti/go/pkg/mod/github.com/meilisearch/meilisearch-go@v0.9.1/client.go:239 +0x115
main.main()
	/Users/deshetti/Projects/playground/player-database/index-players/main.go:149 +0x406
exit status 2
```

Here is how I am using the above in my code. I am new to both Golang and Meilisearch, excuse me if I am missing something simple.

```
	// Creates an index in Meilisearch with the name players
	createIndex("players")

	// Index the players
	var client = meilisearch.NewClient(meilisearch.Config{
		Host: meiliURI,
	})

	updateIDRes, err := client.
		Documents("players").
		AddOrUpdate(articles)

	client.WaitForPendingUpdate(context.TODO(), 60*time.Second, "players", updateIDRes)
	// client.DefaultWaitForPendingUpdate("players", updateIDRes)

	if err != nil {
		log.Fatal(err)
	}
```

Any help is greatly appreciated. Thanks.

**Comment by alexisvisco** [comment]
There is a default timeout in the golang client, to index a bunch of documents you need to custom the timeout like that: 

```go
&http.Client{
  Timeout: time.Second * 10,
}
```

And pass it to this function https://github.com/meilisearch/meilisearch-go/blob/master/client.go#L47 (instead of using NewClient)

**Comment by deshetti** [comment]
Thanks @alexisvisco, it worked.
